---

- name: DOCKER DEBIAN | Uninstall old version
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: DOCKER DEBIAN | Install prerequisites packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present

- name: DOCKER DEBIAN | Add apt key
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present

- name: DOCKER DEBIAN | Add repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes
